config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  resources :todos

  post 'login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user1.rb
class User1 < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:create]
  
    def create
      user = User1.find_by(username: params[:username])
      if user&.authenticate(params[:password])
        token = encode_token({ user_id: user.id })
        render json: { token: token}, status: :ok
      else
        render json: { error: 'Invalid username or password'}, status: :unauthorized
      end
    end
  
    private
  
    def encode_token(payload)
      JWT.encode(payload, Rails.application.secrets.secret_key_base)
    end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user

  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to @todo
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description, :completed)
  end

  private

  def authenticate_user
    token = request.headers['Authorization'].split(' ')[1] rescue nil
    if token
      begin
        decoded_token = JWT.decode(token, Rails.application.secrets.secret_key_base)[0]
        @current_user = User1.find(decoded_token['user_id'])
      rescue JWT::DecodeError
        render json: { error: 'Unauthorized' }, status: :unauthorized
      end
    else
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
      <%= link_to 'Profile', edit_user_registration_path %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: todo do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% todo.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% todo.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<h1>Todos</h1>

<ul>
    <% @todos.each do |todo| %>
      <li>
        <%= form_with model: todo, local: true do |form| %>
        <%= form.check_box :completed, checked: todo.completed,
             onchange: 'this.form.submit();' %>
        <%= link_to todo.title, todo %>
        <% end %>
      </li>
    <% end %>
</ul>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<h1> <%= @todo.title %></h1>
<p><%= @todo.description %>

<ul>
    <li><%= link_to 'Edit', edit_todo_path(@todo) %></li>
    <li><%= link_to 'Destroy', todo_path(@todo), data: {
                    turbo_method: :delete,
                    turbo_confirm: 'Are you sure?'
                  } %></li>
</ul>